services:
  db:
    image: postgres:16
    container_name: postgres_conhecimento
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: senha123
      POSTGRES_DB: conhecimento
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: backend_conhecimento
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: admin
      DB_PASSWORD: senha123
      DB_NAME: conhecimento

  frontend:
    build:
      context: ./frontend
    container_name: frontend_container
    ports:
      - "4200:4200"
      - "49153:49153"
    depends_on:
      - backend
    stdin_open: true
    tty: true
    volumes:
      - ./frontend:/app
      - /app/node_modules 
    command: npm start

volumes:
  db_data:
  node_modules:
